FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# zależności systemowe – minimalnie, bez cudów
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

# jeśli requirements.txt jest w głównym katalogu repo, skopiuj go tu ręcznie
COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# kod projektu
COPY . /app/

EXPOSE 8000

# Na razie devowo – jak chcesz, potem zmienimy na gunicorna
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
