# Generated by Django 5.2.8 on 2025-11-15 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(max_length=100, verbose_name='Stanowisko')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='Czy przełożony')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='shift_manager.employee', verbose_name='Przełożony')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('shift_type', models.CharField(choices=[('morning', 'Poranna (6:00-14:00)'), ('afternoon', 'Popołudniowa (14:00-22:00)'), ('night', 'Nocna (22:00-6:00)'), ('full', 'Cały dzień (8:00-16:00)')], max_length=20, verbose_name='Typ zmiany')),
                ('start_time', models.TimeField(verbose_name='Początek')),
                ('end_time', models.TimeField(verbose_name='Koniec')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shift_manager.employee')),
            ],
            options={
                'verbose_name': 'Zmiana',
                'verbose_name_plural': 'Zmiany',
                'ordering': ['-date', 'start_time'],
                'unique_together': {('employee', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('swap', 'Zamiana zmiany'), ('cancel', 'Anulowanie zmiany'), ('modify', 'Modyfikacja godzin'), ('add', 'Dodanie zmiany')], max_length=20, verbose_name='Typ wniosku')),
                ('new_date', models.DateField(blank=True, null=True, verbose_name='Nowa data')),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='Nowy początek')),
                ('new_end_time', models.TimeField(blank=True, null=True, verbose_name='Nowy koniec')),
                ('new_shift_type', models.CharField(blank=True, choices=[('morning', 'Poranna (6:00-14:00)'), ('afternoon', 'Popołudniowa (14:00-22:00)'), ('night', 'Nocna (22:00-6:00)'), ('full', 'Cały dzień (8:00-16:00)')], max_length=20)),
                ('reason', models.TextField(verbose_name='Powód')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('approved', 'Zaakceptowany'), ('rejected', 'Odrzucony')], default='pending', max_length=20, verbose_name='Status')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notatki przełożonego')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to='shift_manager.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='shift_manager.employee', verbose_name='Rozpatrzony przez')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='shift_manager.shift', verbose_name='Zmiana')),
                ('swap_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests', to='shift_manager.shift', verbose_name='Zmiana do zamiany')),
                ('swap_with_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests', to='shift_manager.employee', verbose_name='Zamiana z')),
            ],
            options={
                'verbose_name': 'Wniosek o zmianę',
                'verbose_name_plural': 'Wnioski o zmiany',
                'ordering': ['-created_at'],
            },
        ),
    ]
