# Generated by Django 5.2.8 on 2025-11-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
    ]
