# Generated by Django 5.2.8 on 2025-11-15 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0002_alter_shift_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('shift_type', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('created', 'Utworzono'), ('updated', 'Zaktualizowano'), ('merged', 'Scalono'), ('deleted', 'Usunięto')], max_length=20)),
                ('source', models.CharField(blank=True, help_text="Źródło zmiany, np. 'manual', 'request', 'merge', 'seed'", max_length=50)),
                ('extra_info', models.TextField(blank=True, help_text='Dodatkowe informacje (np. poprzednie ID, powód zmiany)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_shift_changes', to=settings.AUTH_USER_MODEL, verbose_name='Zmienione przez')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_history', to='shift_manager.employee', verbose_name='Pracownik')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='shift_manager.shift', verbose_name='Powiązana zmiana')),
            ],
            options={
                'verbose_name': 'Historia zmiany',
                'verbose_name_plural': 'Historia zmian',
                'ordering': ['-created_at'],
            },
        ),
    ]
