# Generated by Django 5.2.8 on 2025-11-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0003_shifthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa działu')),
                ('short_name', models.CharField(max_length=30, unique=True, verbose_name="Skrót (np. 'Kuchnia')")),
                ('color', models.CharField(default='#0d6efd', help_text='Kolor do oznaczania zmian, np. #0d6efd', max_length=7, verbose_name='Kolor')),
            ],
            options={
                'verbose_name': 'Dział',
                'verbose_name_plural': 'Działy',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('staff', 'Pracownik'), ('supervisor', 'Brygadzista / Lider'), ('manager', 'Kierownik'), ('director', 'Dyrektor')], default='staff', max_length=20, verbose_name='Rola'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shift_manager.department', verbose_name='Dział'),
        ),
    ]
