# Generated by Django 5.2.8 on 2025-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0004_department_employee_role_employee_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date', 'status', 'start_time'], 'verbose_name': 'Zmiana', 'verbose_name_plural': 'Zmiany'},
        ),
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('planned', 'Zaplanowana'), ('confirmed', 'Potwierdzona'), ('absence', 'Nieobecność'), ('sick', 'L4'), ('replacement', 'Zastępstwo potrzebne')], default='planned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Poranna'), ('afternoon', 'Popołudniowa'), ('night', 'Nocna'), ('full', 'Cały dzień')], max_length=20, verbose_name='Typ zmiany'),
        ),
        migrations.AlterField(
            model_name='shiftchangerequest',
            name='new_shift_type',
            field=models.CharField(blank=True, choices=[('morning', 'Poranna'), ('afternoon', 'Popołudniowa'), ('night', 'Nocna'), ('full', 'Cały dzień')], max_length=20),
        ),
    ]
